### ISSUE TITLE
Error in Swift 4.2/Xcode 10

### ISSUE THREAD

**Issue by waterskier2007** [fousa/trackkit#3]
/Users/<username>/Documents/Projects/TrailMap/Pods/TrackKit/Sources/Parser/Extensions/String+Range.swift:22:28: Cannot invoke initializer for type 'Range<_>' with an argument list of type '(Range<String.Index>)'

**Comment by miktap** [comment]
I would really appreciate a fix to this issue. Do you have any time to look at this @fousa?

**Comment by fousa** [comment]
I will take a look at this tonight!

**Comment by miktap** [comment]
👍

**Comment by BennettSmith** [comment]
Hello @fousa.  I am also running into this build error when trying to use TrackKit with Xcode 10.  Do you have any thoughts on how we might approach solving this?  If you can point me in the right direction, I'm happy to take a stab at trying to fix it and submit a PR.

**Comment by fousa** [comment]
Fixes are pushed to the master branch.

Enjoy TrackKit with Xcode 10 and sorry for the delay...

**Comment by waterskier2007** [comment]
@fousa thanks so much! Are you planning to push a new version to CocoaPods?

**Comment by miktap** [comment]
Apologies for pushing but could you also do a new release with this fix @fousa?

**Comment by fousa** [comment]
Hi @miktap, the new version (2.4.1) is available on Cocoapods!
